# Generated by Django 3.2.9 on 2021-11-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211117_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество'),
        ),
    ]
