# Generated by Django 3.2.9 on 2021-11-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211118_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_username',
            field=models.CharField(max_length=255, verbose_name='Логин покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(verbose_name='Товары'),
        ),
    ]
